apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: default
spec:
  selector:
    app: position-simulator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
