apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: default
spec:
  selector:
    app: fleetman-position-simulator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30081
  type: NodePort
